# Porta dinâmica: O Render define a porta automaticamente, se não houver, usa 8085
server.port=${PORT:8085}

# Conexão com o Banco de Dados (As etiquetas que preencheremos no site do Render)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Hibernate: Atualiza as tabelas no MySQL automaticamente sem apagar dados
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect